export const CONST_FETCH_MOVIE_COLLECTIONS = 'FETCH_MOVIE_COLLECTIONS';
export const CONST_FETCH_MOVIE_DETAIL = 'FETCH_MOVIE_DETAIL';
export const CONST_SET_CREDENTIALS = 'SET_CREDENTIALS';
export const CONST_ACCESSTOKEN = 'accessToken';
export const CONST_CREDENTIALS = 'credentials';
